eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      currency-conversion:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        event-consumer-buffer-size: 10
        failureRateThreshold: 60
        minimumNumberOfCalls: 6
        permittedNumberOfCallsInHalfOpenState: 2
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 3s
        
server:
  port: 8003
spring:
  application:
    name: currency-conversion
